import React from 'react';
import Head from 'next/head';

type IProps = {
 
  title: string
}

const SEO = (props: IProps) => {



  return (
    <Head>
      <title>Employee</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default SEO;